services:
  - type: web
    name: capachica-turismo-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://capachica-turismo-backend.onrender.com
    startCommand: ""
